#!/usr/bin/env php
<?php
/**
 * This file is part of Notadd.
 * @author TwilRoad <269044570@qq.com>
 * @copyright (c) 2016, iBenchu.org
 * @datetime 2016-10-21 13:32
 */
define('NOTADD_START', microtime(true));
require __DIR__ . '/vendor/autoload.php';
$compiledPath = __DIR__ . '/storage/bootstraps/compiled.php';
if(file_exists($compiledPath)) {
    require $compiledPath;
}
$application = new \Notadd\Foundation\Application(realpath(__DIR__));
$application->singleton(Illuminate\Contracts\Http\Kernel::class, Notadd\Foundation\Http\Kernel::class);
$application->singleton(Illuminate\Contracts\Console\Kernel::class, Notadd\Foundation\Console\Kernel::class);
$application->singleton(Illuminate\Contracts\Debug\ExceptionHandler::class, Notadd\Foundation\Exception\Handler::class);
$kernel = $application->make(Illuminate\Contracts\Console\Kernel::class);
$status = $kernel->handle($input = new Symfony\Component\Console\Input\ArgvInput, new Symfony\Component\Console\Output\ConsoleOutput);
$kernel->terminate($input, $status);
exit($status);