name: %env:APP_NAME,My Application%
env: %env:APP_ENV,production%
debug: %env:APP_DEBUG,false%
url: %env:APP_URL,http://localhost%
timezone: %env:APP_TIMEZONE,PRC%
locale: %env:APP_LOCALE,zh-cn%
fallback_locale: %env:APP_LOCALE_FALLBACK,zh-cn%
key: %env:APP_KEY%
cipher: 'AES-256-CBC'
log: %env:APP_LOG,daily%
log_level: %env:APP_LOG_LEVEL,debug%
providers:
    - Illuminate\Auth\AuthServiceProvider
    - Illuminate\Auth\Passwords\PasswordResetServiceProvider
    - Illuminate\Broadcasting\BroadcastServiceProvider
    - Illuminate\Bus\BusServiceProvider
    - Illuminate\Cookie\CookieServiceProvider
    - Illuminate\Encryption\EncryptionServiceProvider
    - Illuminate\Hashing\HashServiceProvider
    - Illuminate\Pagination\PaginationServiceProvider
    - Illuminate\Pipeline\PipelineServiceProvider
    - Illuminate\Queue\QueueServiceProvider
    - Illuminate\Session\SessionServiceProvider
    - Illuminate\Validation\ValidationServiceProvider
    - Notadd\Foundation\Addon\AddonServiceProvider
    - Notadd\Foundation\Attachment\AttachmentServiceProvider
    - Notadd\Foundation\Composer\ComposerServiceProvider
    - Notadd\Foundation\Console\ConsoleServiceProvider
    - Notadd\Foundation\Database\MigrationServiceProvider
    - Notadd\Foundation\Debug\DebugServiceProvider
    - Notadd\Foundation\Editor\EditorServiceProvider
    - Notadd\Foundation\Extension\ExtensionServiceProvider
    - Notadd\Foundation\Flow\FlowServiceProvider
    - Notadd\Foundation\Image\ImageServiceProvider
    - Notadd\Foundation\JWTAuth\JWTAuthServiceProvider
    - Notadd\Foundation\Mail\MailServiceProvider
    - Notadd\Foundation\Member\MemberServiceProvider
    - Notadd\Foundation\Navigation\NavigationServiceProvider
    - Notadd\Foundation\Notification\NotificationServiceProvider
    - Notadd\Foundation\Permission\PermissionServiceProvider
    - Notadd\Foundation\SearchEngine\SearchEngineServiceProvider
    - Notadd\Foundation\Theme\ThemeServiceProvider
    - Notadd\Foundation\Translation\TranslationServiceProvider
    - Notadd\Foundation\Yaml\YamlServiceProvider
    - Notadd\Foundation\Http\HttpServiceProvider
    - Notadd\Foundation\Administration\AdministrationServiceProvider
    - Notadd\Installer\InstallerServiceProvider
aliases:
    App: Illuminate\Support\Facades\App
    Artisan: Illuminate\Support\Facades\Artisan
    Auth: Illuminate\Support\Facades\Auth
    Blade: Illuminate\Support\Facades\Blade
    Cache: Illuminate\Support\Facades\Cache
    Config: Illuminate\Support\Facades\Config
    Cookie: Illuminate\Support\Facades\Cookie
    Crypt: Illuminate\Support\Facades\Crypt
    DB: Illuminate\Support\Facades\DB
    Eloquent: Illuminate\Database\Eloquent\Model
    Event: Illuminate\Support\Facades\Event
    File: Illuminate\Support\Facades\File
    Gate: Illuminate\Support\Facades\Gate
    Hash: Illuminate\Support\Facades\Hash
    Lang: Illuminate\Support\Facades\Lang
    Log: Illuminate\Support\Facades\Log
    Mail: Illuminate\Support\Facades\Mail
    Notification: Illuminate\Support\Facades\Notification
    Password: Illuminate\Support\Facades\Password
    Queue: Illuminate\Support\Facades\Queue
    Redirect: Illuminate\Support\Facades\Redirect
    Redis: Illuminate\Support\Facades\Redis
    Request: Illuminate\Support\Facades\Request
    Response: Illuminate\Support\Facades\Response
    Route: Illuminate\Support\Facades\Route
    Schema: Illuminate\Support\Facades\Schema
    Session: Illuminate\Support\Facades\Session
    Storage: Illuminate\Support\Facades\Storage
    URL: Illuminate\Support\Facades\URL
    Validator: Illuminate\Support\Facades\Validator
    View: Illuminate\Support\Facades\View